using EVServiceCenter.Core.Domains.Payments.Constants;

namespace EVServiceCenter.Core.Domains.Payments.DTOs.Requests;

/// <summary>
/// Request body for completing a mock payment (VNPay/MoMo) in demo mode
/// </summary>
public class MockPaymentCompleteRequestDto
{
    /// <summary>
    /// Payment code generated by the system (e.g. PAY-20251025-0001)
    /// </summary>
    public string PaymentCode { get; set; } = string.Empty;

    /// <summary>
    /// Payment gateway to simulate. Supported: VNPay, MoMo. Default: VNPay
    /// </summary>
    public string Gateway { get; set; } = PaymentMethodType.VNPay;

    /// <summary>
    /// Whether to simulate a successful payment
    /// </summary>
    public bool Success { get; set; } = true;

    /// <summary>
    /// Optional override amount. If null, the invoice outstanding amount is used.
    /// </summary>
    public decimal? Amount { get; set; }
}
